sudo: false
language: php
php:
  - 7.0
  - 7.1

before_script:
  - composer require php-coveralls/php-coveralls
  - composer install -n

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs

after_script: vendor/bin/coveralls
